services:
  bot:
    image: institute-bot:latest
    restart: always
    env_file: .env
  db:
    image: mysql:latest
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    # expose:
    #   - 3306

volumes:
  db_data:
